# Flask container
version: "3.0"
services:
  web:
    container_name: pee_df_adhoc_requests
    build: .
    ports:
      - "4280:4280"
    env_file:
      - src\enter_app_name\.env
# networks:
#   default:
#     external: true
#     name: backend_default # Need to connect to same network as sql container
